version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: node-notifier
    versions:
    - 8.0.1
  - dependency-name: elliptic
    versions:
    - 6.5.3
